### ISSUE TITLE
Error when using with minikube

### ISSUE THREAD

**Issue by mikelnrd** [GoogleCloudPlatform/cloud-build-local#40]
Hi

Not sure if the error is with minikube or container-builder-local, but thought I'd post here first.

I'm seeing 
```text
2017/11/28 14:51:03 Error updating token in metadata server: Post http://localhost:8082/token: dial tcp [::1]:8082: getsockopt: connection refused
```
when running container-builder-local with the same Docker host as the minikube VM (On Mac, using xhyve driver).

### More info

First I set up minikube on my Mac following the [hello-node minikube tutorial](https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/).

I was able to set up minikube, and build the hello-node docker image following that tutorial using docker build. I was also able to build the same hello-node using container builder in the cloud no problem, and also got the container-builder-local working. 

What I want to do is build the containers with the same Docker host as my minikube VM like the tutorial says, so that I can build locally using container-builder-local and have the images available in minikube. Unfortuantely I get an error which I'm hoping you can help me.

The hello-node minikube tutorial says:

> Because this tutorial uses Minikube, instead of pushing your Docker image to a registry, you can simply build the image using the same Docker host as the Minikube VM, so that the images are automatically present. To do so, make sure you are using the Minikube Docker daemon:
`eval $(minikube docker-env)` which does:

```bash
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.64.13:2376"
export DOCKER_CERT_PATH="/Users/mike/.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minikube docker-env)
```

So after I run `eval $(minikube docker-env)` I can use the normal docker build commands from the tutorial to successfully build the hello-node image using the same Docker host as the Minikube VM. 

**However...** when I use the following `cloudbuild.yaml` 

```yaml
    steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hello-node-image', '.' ]
    images:
    - 'gcr.io/$PROJECT_ID/hello-node-image'
```
I can get it to work no problem for the cloud version of container-builder AND my regular docker host (using `eval $(minikube docker-env -u)` to undo the switch to the minikube Docker host). But I get the following error when I run this line after switching to the minikube Docker host with `eval $(minikube docker-env)`

```bash
container-builder-local --config=cloudbuild.yaml --dryrun=false .
```
I get the following error:

```text
2017/11/28 14:50:49 Warning: The server docker version installed (17.06.0-ce) is different from the one used in GCB (17.06.1-ce)
2017/11/28 14:50:49 Warning: The client docker version installed (17.09.0-ce) is different from the one used in GCB (17.06.1-ce)
Using default tag: latest
latest: Pulling from cloud-builders/metadata
Digest: sha256:3f52605df8532eca6aff1fa9d0cb035b07bfb68bedf0ffd5b919c84f41aa7685
Status: Image is up to date for gcr.io/cloud-builders/metadata:latest
2017/11/28 14:50:59 Started spoofed metadata server
2017/11/28 14:51:00 status changed to "BUILD"
BUILD
Pulling image: gcr.io/cloud-builders/docker
Unable to find image 'gcr.io/cloud-builders/docker:latest' locally
latest: Pulling from cloud-builders/docker
660c48dd555d: Already exists
4c7380416e78: Already exists
421e436b5f80: Already exists
e4ce6c3651b3: Already exists
be588e74bd34: Already exists
10d78c1521df: Pulling fs layer
3a9f6555ca9b: Pulling fs layer
2017/11/28 14:51:03 Error updating token in metadata server: Post http://localhost:8082/token: dial tcp [::1]:8082: getsockopt: connection refused
2017/11/28 14:51:05 Error updating token in metadata server: Post http://localhost:8082/token: dial tcp [::1]:8082: getsockopt: connection refused
2017/11/28 14:51:07 Error updating token in metadata server: Post http://localhost:8082/token: dial tcp [::1]:8082: getsockopt: connection refused
2017/11/28 14:51:10 Error updating token in metadata server: Post http://localhost:8082/token: dial tcp [::1]:8082: getsockopt: connection refused
2017/11/28 14:51:12 Error updating token in metadata server: Post http://localhost:8082/token: dial tcp [::1]:8082: getsockopt: connection refused
2017/11/28 14:51:14 Error updating token in metadata server: Post http://localhost:8082/token: dial tcp [::1]:8082: getsockopt: connection refused
2017/11/28 14:51:16 Error updating token in metadata server: Post http://localhost:8082/token: dial tcp [::1]:8082: getsockopt: connection refused
```

I'v tried googling the error but didn't find anything. I've also made sure to run `docker-credential-gcr configure-docker` and `google auth login` but I get the same error. Would love to get this working so can use the same container-builder and kubectl commands locally and in production. Thanks in advance for any help.

**Comment by Philmod** [comment]
Hey Michael,

Thanks for reporting this. We have never tried running the tool with minikube yet.

A few questions that might help you going forward:
1. If minikube is using the same docker from the host, why is that better to build from within minikube? `docker images` should be the same if the same docker is used.
2. I'm not familiar with minikube, it seems like there is a service using port 8082 that blocks the local builder from contacting the spoofed metadata server (used with the local builder).

I wish I could help you more, but I really don't know much about minikube.

**Comment by mikeleonard** [comment]
Hey Phil thanks for the quick response!

Re question 2, yeah it looks like the spoofed metadata server isn't reachable. Perhaps it's blocked or just isn't running. **EDIT: I think I've worked out why (see response to your question 2 below).

#### Response to question 1:
I'm a beginner with all this - but I think the idea is that my Mac and minikube are using a different Docker host (one is my Mac, the other is minikube's xhyve linux machine (like a virtual box image) that minikube runs inside of, presumably because it needs a linux not mac environment). 

I've just tested it to make sure: I can run `eval $(minikube docker-env)` and `eval $(minikube docker-env -u)` to jump between the two. I see different images when I run `docker images`. 

#### The problem is...

If I build a docker image locally using my Mac's docker host, then I need to push it to a registry and then have minikube pull it again. What I would be able to do if this works is simply use container-builder-local to build the images straight into the xhyve virtual machine where minikube is running so that they are local to minikube.

Following the minikube tutorial it was easy to get this working with normal normal docker commands after running `eval $(minikube docker-env)` ... so I can use docker build locally and container-builder for cloud builds... but ideally I'd like to get container-builder-local working with minikube. That way, the way I build locally is the same as the way I build in the cloud (container builder) and the way I deploy locally (minikube) is the way I deploy in the cloud (gke).


#### Re question 2

I've just had a thought. The error I'm getting is `Post http://localhost:8082/token: dial tcp [::1]:8082: getsockopt: connection refused`.
When I run `minikube status` it tells me:
```text
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.64.13
```
and when I run `minikube dashboard` it opens the kubernetes dashboard at 192.168.64.13:30000

So i'm guessing the problem is the spoofed metadata server is actually at http://192.168.64.13:8082/token

I ran `container-builder-local --config=cloudbuild.yaml --dryrun=false .` again, and when it was looping to retry the POST to http://localhost:8082/token, I ran `curl http://192.168.64.13:8082`. It doesn't return it just hangs waiting... but curling a made up address like `curl http://192.168.64.13:8081` immediately returns `Connection refused`... so that leads me to believe `http://192.168.64.13:8082` does indeed exist and is the spoofed metadata server.

#### Quick questions for you

1. Do you have any other ideas for how I can test to make sure that's the problem? Perhaps you know the format I can use to post to the spoofed metadata server manually to see if that works?
2. And.. assuming that's the problem... any idea of a solution? I guess container-builder-local would either need to realise it's being used with minikube and get the ip to call from `minikube status` or something similar... or would need to have a command-line flag where you could pass the minikube -vm's ip.
3. Worth me asking over at the minikube repo do you think?

Thanks for the quick reply. Sorry for the long message, shouldn't have had that second coffee.

**Comment by mikeleonard** [comment]
Haha so I just realised container-builder-local is written in Go, I thought it was in Python like the gcloud cli. That made me not so scared to try to fix it, and good news I think I've managed it. 

Changing this...

```go
func (r RealUpdater) getAddress() string {
	if r.Local {
		return "localhost:8082"
	}
	return metadataHostedIP
}
``` 
to this...
```go
func (r RealUpdater) getAddress() string {
	if r.Local {
		return "192.168.64.13:8082"
	}
	return metadataHostedIP
}
```
made it work for me.

In `metadata.go` you have the command: 
```go
cmd = []string{"docker", "run", "-d", "-p=8082:80", "--name=metadata", metadataImage}
``` 

Because I've run `eval $(minikube docker-env)` like the minikube tutorial says to, I have set the docker host environment variable (before it was empty) because `minikube docker-env` outputs:
```bash
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.64.13:2376"
export DOCKER_CERT_PATH="/Users/mike/.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minikube docker-env)
```

This means that the spoofed metadata server docker image is started up in on 192.168.64.13 instead of localhost (ie it's started up wherever the env variable DOCKER_HOST points to)

So my proposal for you...

How about rewriting `RealUpdater` to use the `DOCKER_HOST`  environment variable to extract the address `192.168.64.13` (ie the minikube-vm's ip), and use localhost if `DOCKER_HOST` is not set?

**Comment by Philmod** [comment]
I guess that could work? Feel free to provide a PR :)

**Comment by pravinchandar** [comment]
I ran into a similar issue, I ended up using `socat` to forward the traffic to the docker host
`socat TCP-LISTEN:8082,fork TCP:DOCKER_HOST:8082`

**Comment by duanshiqiang** [comment]
I ran into the similar issue with docker-machine on macos. @pravinchandar your solution also works with docker-machine, thanks!

**Comment by phedinkus** [comment]
I also got hung up with docker machine. It took me a long time to find this solution. I believe an update to the readme (and instructions on gcloud documentation) are in order.

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
